# Generated by Django 3.1.5 on 2021-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=80, verbose_name='full name')),
                ('membership_id', models.CharField(blank=True, default='', max_length=1000000, null=True, verbose_name='Membership id')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('citizenship', models.CharField(blank=True, max_length=225, verbose_name='citizenship')),
                ('education', models.CharField(blank=True, max_length=225, verbose_name='education')),
                ('current', models.CharField(blank=True, max_length=225, verbose_name='current')),
                ('permoment', models.CharField(max_length=225, verbose_name='permoment')),
                ('member_of_ngo', models.CharField(blank=True, max_length=225, verbose_name='member of ngo')),
                ('usa_year', models.IntegerField(null=True, verbose_name='usa year')),
                ('reasons', models.TextField(blank=True, verbose_name='reasons')),
                ('mention', models.TextField(blank=True, verbose_name='mention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=80, verbose_name='Subject')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
