# Generated by Django 3.1.5 on 2021-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210128_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usa_year',
            field=models.IntegerField(null=True, verbose_name='usa year'),
        ),
    ]
