# Generated by Django 3.1.5 on 2021-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210128_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2020-10-10', verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
