# Generated by Django 3.1.5 on 2021-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210129_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationuser',
            name='membership_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=1000000, null=True, verbose_name='Membership id'),
        ),
    ]
