# Generated by Django 3.1.5 on 2021-01-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210129_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
