# Generated by Django 3.1.5 on 2021-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_donationuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationuser',
            name='membership_id',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True, verbose_name='Membership id'),
        ),
    ]
