# Generated by Django 3.1.5 on 2021-01-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210130_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationuser',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=225, verbose_name='citizenship'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='current',
            field=models.CharField(blank=True, max_length=225, verbose_name='current'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='education',
            field=models.CharField(blank=True, max_length=225, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='member_of_ngo',
            field=models.CharField(blank=True, max_length=225, verbose_name='member of ngo'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='mention',
            field=models.TextField(blank=True, verbose_name='mention'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='donationuser',
            name='reasons',
            field=models.TextField(blank=True, verbose_name='reasons'),
        ),
    ]
