# Generated by Django 3.1.5 on 2021-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210131_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
