# Generated by Django 3.1.5 on 2021-02-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_message_to_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationuser',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
