# Generated by Django 3.1.5 on 2021-01-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='mail',
        ),
    ]
