# Generated by Django 3.1.5 on 2021-01-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210129_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mail',
            field=models.EmailField(max_length=125, unique=True, verbose_name='email'),
        ),
    ]
