# Generated by Django 3.1.5 on 2021-01-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210129_1306'),
        ('core', '0006_auto_20210129_1922'),
    ]

    operations = [
    ]
